### PR TITLE
Added settings docs and fixed event_data links

### PR DESCRIPTION
**Pull request by solarkennedy**
This is to address 
https://groups.google.com/forum/#!topic/sensu-users/CQ4hCOHqo1Q

### CODE REVIEW

**Comment by solarkennedy** [comment]
Bump? Its been a few months. I can rebase to include .16 but I don't want to do this forever.

**Comment by calebhailey** [comment]
OHAI @solarkennedy! :wave: 

First off, please accept our apologies for the belated response on this PR. We've never done a very good job with community contributions to Sensu docs, but we're trying to change that. Having said that, I would go ahead and merge this, but it's for such an old version of Sensu (because of our failure to stay up to date w/ sensu-docs PRs), that I'm going to target this in the upcoming 0.23 release documentation. 

We're hoping to finally ship some documentation around extensions with the 0.23 docs, and your examples will be helpful. 

Thanks for using Sensu! #monitoringlove

**Comment by solarkennedy** [comment]
This is fine, do what you gotta do.

**Review by majormoses — COMMENTED** [review]
Overall looks good, unfortunately that page no longer exists I think this needs to be moved to: https://sensuapp.org/docs/1.2/reference/handlers.html#handler-configuration. Also a couple of things to consider enhancing while we are at it:
- link to the function in sensu plugins like [this](https://github.com/sensu-plugins/sensu-plugin/blob/v2.1.0/lib/sensu-plugin/utils.rb#L21-L23)
- link and explanation on how you can test handlers by setting the ENV vars ad-hoc: https://github.com/sensu-plugins/sensu-plugin/blob/v2.1.0/lib/sensu-plugin/utils.rb#L21-L23

Certainly understand that it might not be a priority anymore and I think it might be good for sensu to pick this up to fixup (the location) and enhance. This is the price that needs to be paid when PRs go unreviewed for a while.

**Comment by mbbroberg** [comment]
I'm working on it right now, so 👍

**Comment by mbbroberg** [comment]
Pulled into Handler and Extensions docs for 1.2 here: 
10c870a

**Comment by mbbroberg** [comment]
I'm happy to say I got this essential parts of this document into our existing 1.2 release and this is a PR that's ready to close. This feels like the right face to make rn: 

tenor 12

❤️

**Pull request closed without merging**
