### PR TITLE
Added a FAQs about stashes and cleaned up some formatting.

### PR DESCRIPTION
**Pull request by joestump**

### CODE REVIEW

**Comment by joestump** [comment]
Should have created a branch; there's now two different edits to the FAQ in here.

**Comment by joestump** [comment]
Also, I looked through the code and didn't see an API client library in there. I'm assuming there's something like `Sensu::API::Client::#remove` or something in the code. If you point me at it, I'll add that in there as well for the Ruby nerds.

**Comment by portertech** [comment]
@joestump Awesome, thank you for the FAQ updates! Because checks and handlers can be written in any language, there hasn't been much (if any) effort put towards an API client, since languages like Ruby already have access to some nifty libraries like rest-client etc. Is there a need\* for an API client?

**Comment by portertech** [comment]
I'm going to merge these changes, I should have them published this evening.

**Comment by joestump** [comment]
I can see why it'd be handy. I don't personally need one though.

**Pull request merged**
