### PR TITLE
Update dashboards_uchiwa.md

### PR DESCRIPTION
**Pull request by dillera**
Added in notes for clearing redis cache for an upgrade. Otherwise uchiwa fails as here: https://github.com/sensu/uchiwa/issues/90

### CODE REVIEW

**Comment by dillera** [comment]
notes on upgrading sensu and installing uchiwa. You need to clear the redis cache first before you start the new dashboard.

**Comment by palourde** [comment]
It might make more sense to add it to http://sensuapp.org/docs/0.13/upgrading since I don't think this issue is specific to Uchiwa; all dashboards could fail because the API isn't providing the proper data until the redis cache is flushed.

**Comment by dillera** [comment]
It makes sense to have it in both places. Accept this and I'll make a new request for the upgrading page.

**Comment by palourde** [comment]
I'm not maintaining this repo so I'll leave this to the concerned persons!

**Comment by portertech** [comment]
Flushing Redis has no effect on Uchiwa, only the Sensu API.

**Pull request closed without merging**
