### PR TITLE
stashes-expiration details

### PR DESCRIPTION
**Pull request by jaimegago**
added some info about stashes expiration and an example in the stashes API

### CODE REVIEW

**Comment by jamtur01** [comment]
Thanks for your contribution. Can you please squash these down. Thanks!

**Comment by jaimegago** [comment]
I think it’s good to go now?
(followed this http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request for the rebasing)

**Comment by jamtur01** [comment]
@portertech you okay with this?

**Comment by portertech** [comment]
:+1:

**Pull request merged**
