### PR TITLE
Integration documentation improvements

### PR DESCRIPTION
**Pull request by calebhailey**
I missed a few commits in https://github.com/sensu/sensu-docs/pull/383...

### CODE REVIEW

**Comment by calebhailey** [comment]
...a few BIG commits.

**Comment by calebhailey** [comment]
I guess the commits were accurately described as being derpy because I pushed them to the heavywater/sensu-docs fork instead of here. Anyway, this is the good stuff. :)

**Comment by agoddard** [comment]
:+1:

**Comment by agoddard** [comment]
🍧 :shipit:

**Pull request merged**
