### PR TITLE
Pure markdown

### PR DESCRIPTION
**Pull request by calebhailey**
This is the reformatted documentation for hosting on the new http://sensuapp.org. Probably not ready to be pulled into master, but I would love to see it pulled into a new pure-markdown branch until it's ready for primetime.

### CODE REVIEW

**Comment by calebhailey** [comment]
Thanks @jamtur01 !

**Comment by jamtur01** [comment]
Great update BTW. Happy to see a more flexible solution.

**Comment by calebhailey** [comment]
@jamtur01 thanks! We're going to try to get the new site published this afternoon; I'll be anxious to see what kind of feedback we get; and I'll be very excited to see how much we can improve the documentation now that it's (hopefully) easier to edit. 

I'd still like to add in something to run a local server to preview the changes. Maybe I can strip out the content from the new middleman site and set it up so someone could run `bundle install` then `bundle exec middleman` the see a live reloading syntax highlighted preview at http://localhost:4567/docs/

**Comment by jamtur01** [comment]
That's a good idea. Avoids a lot of errors if people can preview their contributions.

**Comment by calebhailey** [comment]
@jamtur01 preview server added. Give it a try for me?

**Comment by calebhailey** [comment]
OK, I feel good about this PR now. :+1:

**Comment by jamtur01** [comment]
Looks like there's a merge conflict?

**Comment by calebhailey** [comment]
@jamtur01 to merge into master?

**Pull request merged**
