### PR TITLE
Review 150209 added gsoc 2015 ideas page

### PR DESCRIPTION
**Pull request by kalabiyau**

### CODE REVIEW

**Comment by mattyjones** [comment]
### General refactoring of community plugins code base

**Brief explanation:**

This is a huge task but in a nutshell each repo should be looked at as a self sustaining entity. All the binaries in it should be broken down into libraries and any common code should be shared. All code should be Ruby, no shell or python. New stuff can/will still be accepted in any language but existing stuff should be converted or dropped. This is my major pain point and I would be able to mentor on this as I am already doing it whenever I get the chance.

**Expected outcome:**
- Code Climate > 2.0 on any repo that is being actively refactored
- No code duplication
- Standard Ruby coding practices
- Ephemeral data whenever needed, no traces let on a monitored system including temp files used to store state data
- Favor a pure ruby method, over a arch specific method even at the sacrifice of code complexity ie sys-filesystem gem vs `df`  

**Knowledge prerequisite:**
- basic programing skills, should be functional in Ruby or be willing and able to be functional within a week
- general understanding of ruby std library (see above point)
- general concepts of monitoring or willingness to learn them
- general understanding of how to define, generate, and handle exit codes and what they mean within a sensu/nagios environment
- must believe and understand treating infrastructure as code and why this is necessary in a cloud environment

I will have a full proposal draft for this topic within 48 hours and I will link/PR it here

**Comment by mattyjones** [comment]
### Automated testing framework built around Travis using standard Ruby methods, practices, and tools

**Brief explanation:**

Sensu community plugins are currently in transition to a more robust way of distribution. We want to package each plugin as a part of bigger bundle of similar checks, cover it with tests, and then release as a gem version as part of an automated process. That requires a lot of love from developers and you can help us to build a framework to automate the process of testing our plugins.

**Expected outcome:**

We expect to have the foundation for a set of tools written in Ruby which will allow us to:
- Improve the existing set of development tools including [GIR](https://github.com/sensu-plugins/GIR) which is currently able to bootstrap a plugins development environment including gem and repo creation.
- Create a testing framework which will allow us to run a set of tests within virtual machines and report back the status of that process

**Knowledge prerequisite:**
- general programing skills, should be functional in Ruby or be willing and able to be functional within a week
- general understanding of ruby test procedures (see above point)
- general concepts of monitoring or willingness to learn them
- general understanding of various testing tools including rspec, rubocop, and serverspec
- basic understanding of TravisCI
- basic understanding of infrastructure automation
- must believe and understand treating infrastructure as code and why this is necessary in a cloud environment

**Comment by kalabiyau** [comment]
@mattyjones took in your changes as well. Waiting for final, you've mentioned.

**Comment by mattyjones** [comment]
@portertech @kalabiyau Who is doing the actual mentoring application and how are we applying?  I was already starting to work on that but if it is handled already thats fine.  I can be a primary/secondary admin as well as mentor for either of these tasks, I would be best with the general refactor but can do either.

**Comment by kalabiyau** [comment]
@mattyjones @portertech as I wrote in the email the other day - I will take care of application of Sensu as organization to GSoC 2015 and will manage admin duties. Also I do not mind any help available though. First step we need to take is to finish and deploy that ideas page, as it is part of requirements.

**Comment by mattyjones** [comment]
This is a draft of a completed ideas page incorporating all ideas and thoughts so far mentioned in this thread and via IRC

https://gist.github.com/mattyjones/ee17233d63577807b1a9

**Comment by kalabiyau** [comment]
@mattyjones please let me know if anything here is missing

**Comment by kalabiyau** [comment]
@portertech can we merge and deploy that?

**Comment by mattyjones** [comment]
@kalabiyau  looks good to me.
Great job!  I am on IRC if you need anything

**Comment by kalabiyau** [comment]
@portertech can you please look at this. We need that to apply to gsoc.

**Comment by mattyjones** [comment]
@kalabiyau @portertech 

[Here](http://sensu-plugins.github.io/development/gsoc15) is the completed task list as I see it for the plugins.  I am welcome to thoughts, ideas, and changes.  Clone/pull/push yourself or drop me a note and I will do it.

Thanks

**Comment by calebhailey** [comment]
Closing this due to inactivity from the Sensu team (sorry!). I'd love to see us take another stab at this for 2016 or 2017! #monitoringlove

**Pull request closed without merging**
