### PR TITLE
Changed the command used for email handler

### PR DESCRIPTION
**Pull request by jedops**
Sensu has to read the json data from stdin so the command in the doc
pre this commit will simply send out a blank e-mail with "sensu alert"
as the subject.

This threw me a little when following the docs and this change is similar to one discussed on irc.

### CODE REVIEW

**Comment by portertech** [comment]
`mail` should be accepting the body via stdin.

**Comment by jedops** [comment]
I tried this example and other commands when following the guide. The file.rb example worked as the script is explicitly reading from stdin. For mail the above example only seemed to send out a blank e-mail with the subject 'sensu alert'. I got similar results when I tried using echo instead of mail for debugging. 

After discussing on irc with someone they seemed to think that the example mentioned in the doc would not be enough to send out the json data in the body of the e-mail so I modified the command accordingly and it worked.

I've also seen other people having this issue: http://stackoverflow.com/questions/17799827/sensu-mailer-and-pipe

If pipe is indeed not working as expected for raw commands perhaps I should raise this an issue in the main sensu repo?

**Comment by portertech** [comment]
The example works on several machines, perhaps it's just a version issue. Will investigate tomorrow.

**Comment by portertech** [comment]
`man mail` on bsd shows "name: mail, mailx -- send and receive mail"

**Comment by jedops** [comment]
Hi @portertech sorry about parking this for so long.
I've done some more testing. Basically on ubuntu (or I assume, any distro which uses GNU mail) the mail command will not receive the event json. However, this does work on BSD mail.

To figure this out I ran on vagrant with the following scenarios:

1) Ubuntu GNU mail: Only sends a blank email with the subject 'sensu alert'.
2) Keep everything in 1) the same but run apt-get install bsd-mailx which replaces the default mail client. This does successfully append the event.json.

Not sure how best we'd want to get this across in the documentation, but I think it should get changed as Ubuntu is such a common distro to run sensu on.

**Comment by portertech** [comment]
Your current use of `mail` is not safe, as it's possible for multiple handler executions to clobber the mail body. Need to use a temp file specific to the execution, or we go w/ `mailx`.

**Comment by jedops** [comment]
I see what you mean. I don't think it's possible to capture the handler name for the script and I don't want to use a temp file with a timestamp which could fill up the users /tmp filesystem. I'll change this to add a specific note that this example will only work on bsd-mailx

**Comment by portertech** [comment]
The example can use `mailx`, w/ platform specific installation docs?

**Comment by nstielau** [comment]
@jae2 ping, can we remove the note and just update the example to use `mailx`?

Thanks!

**Comment by portertech** [comment]
@jae2 @nstielau I've pushed/merged https://github.com/sensu/sensu-docs/pull/92 that changes `mail` to `mailx` in the example. If this proves to cause confusion, we'll reopen this and merge it in w/ the note.

@jae2 Thank you for identifying this issue :+1:

**Pull request closed without merging**
