### PR TITLE
API DELETE client invalidate documentation

### PR DESCRIPTION
**Pull request by portertech**

### CODE REVIEW

**Comment by portertech** [comment]
I was going to reference the use of Sensu client signature, but discovered that we have yet to document this feature (0.22.0) - I have created an issue for this task https://github.com/sensu/sensu-docs/issues/566

**Comment by cwjohnston** [comment]
I am left wondering, does using invalidation mean the client is not actually deleted?

**Comment by portertech** [comment]
@cwjohnston states until the client is removed from the registry, not clear enough?

**Comment by cwjohnston** [comment]
> invalidated, disallowing further client keepalives and check results until the client is successfully removed from the client registry.

Clear enough, but...

> invalidated for a specified amount of time (in seconds), instead of on removal from the client registry.

This is the bit that confuses me. Using `invalidate_expire`, upon expiration is the client removed, or is the invalidation removed and the client left intact?

**Review by cwjohnston — APPROVED** [review]

**Pull request merged**
