### PR TITLE
Add section anchors

### PR DESCRIPTION
**Pull request by nstielau**
This will probably mess with the CSS, but I find myself wanting to link to sections directly (especially for larger pagers).  If you link this as is, cool, or want to check on the CSS, either way.  I can bang out a few more anchors once you give the general OK.

### CODE REVIEW

**Comment by nstielau** [comment]
@calebhailey Any comments on the style changes this would introduce?  If not I might just pull, see what they are and we can fix the CSS from there.

**Comment by calebhailey** [comment]
It's been a while since I looked at this but I was planning to switch from
redcarpet to kramdown for Markdown processing. Kramdown has some markdown
extensions that I wasn't too use including custom anchor support. The
syntax is something like:

```
## My Subtitle #{my-subtitle}

Lorem ipsum bla bla bla.
```

See: http://kramdown.gettalong.org/syntax.html#specifying-a-header-id

**Comment by nstielau** [comment]
Cool.  Do you have an ETA for kramdown?  Do you just want to ping a few
folks when you get that out and we can do a sub-section anchor blitz?

This was @portertech's "most glorious and exciting new feature for all of
Sensu for the last week of the shortest month of the year" (paraphrased).

On Fri, Feb 28, 2014 at 10:28 AM, Caleb Hailey notifications@github.comwrote:

> It's been a while since I looked at this but I was planning to switch from
> redcarpet to kramdown for Markdown processing. Kramdown has some markdown
> extensions that I wasn't too use including custom anchor support. The
> syntax is something like:
> 
> ```
> ## My Subtitle #{my-subtitle}
> 
> Lorem ipsum bla bla bla.
> ```
> 
> See: http://kramdown.gettalong.org/syntax.html#specifying-a-header-id
> On Feb 28, 2014 12:02 PM, "nstielau" notifications@github.com wrote:
> 
> > @calebhailey https://github.com/calebhailey Any comments on the style
> > changes this would introduce? If not I might just pull, see what they are
> > and we can fix the CSS from there.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/sensu/sensu-docs/pull/83#issuecomment-36377307>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sensu/sensu-docs/pull/83#issuecomment-36379760
> .

## 

☮
Nick Stielau
206-245-7991

**Comment by portertech** [comment]
@calebhailey Something we can look at for Friday and next week?

**Comment by calebhailey** [comment]
@portertech yes, let's do it. We have this working on some of our other @heavywater projects.

**Comment by calebhailey** [comment]
PR #97 should fix this. /cc @portertech @nstielau

**Pull request closed without merging**
