### PR TITLE
Add upgrade steps for upgrading a 0.10.x (or earlier) installation

### PR DESCRIPTION
**Pull request by ryndaniels**

### CODE REVIEW

**Comment by jamtur01** [comment]
Is this a bug perhaps, i.e. should it be fixed rather than a workaround?

**Comment by ryndaniels** [comment]
I found this here: https://github.com/sensu/sensu/issues/652#issuecomment-27565770, assumed that was the recommended path for upgrading from that earlier version

**Comment by jamtur01** [comment]
Well that's pretty conclusive. :) 

Thanks! :+1:

**Comment by calebhailey** [comment]
@kdaniels did you take advantage of the new "Edit this page" feature on http://sensuapp.org to submit this PR? Just curious to learn if the work we've done there is lowering the barrier for contributions. :smile:

See here for example: http://sensuapp.org/docs/0.12/installing_sensu

NOTE: your update will be published later today.

**Comment by ryndaniels** [comment]
@calebhailey I didn't, but I did use the big red "Fork the docs" button at the top... probably because it was bigger and redder :grinning:

**Comment by nstielau** [comment]
@calebhailey, that shit is so rad.  I think putting up next to the Fork the
Docs might indeed be a clearer CTA as the marketers say.

On Wed, Nov 20, 2013 at 9:15 AM, Katherine Daniels <notifications@github.com

> wrote:
> 
> @calebhailey https://github.com/calebhailey I didn't, but I did use the
> big red "Fork the docs" button at the top... probably because it was bigger
> and redder [image: :grinning:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sensu/sensu-docs/pull/58#issuecomment-28908606
> .

## 

☮
Nick Stielau
206-245-7991

**Comment by calebhailey** [comment]
@kdaniels, @nstielau - excellent feedback. It does feel weird where it's currently at. 

I left the "Fork the Docs" banner there in keeping with the old docs.sensuapp.org, and two giant buttons at the top of the screen felt like too much. Perhaps I should have them swap places? 

Move "Fork the docs" to the position below the table of contents and have it take you to the sensu/sensu-docs repo to fork the whole thing.

Move "Edit this page" to the top (in red) to do in-browser editing. But I like the "Fork" phrasing at the top... so does "Fork the docs" still work? I'm going to play with it. 

/cc @portertech

**Comment by portertech** [comment]
@calebhailey I think these upgrade steps should be mentioned on the 0.9 and 0.10 doc indexes. Undecided on fork vs. edit and placement.

**Comment by calebhailey** [comment]
@kdaniels, @nstielau - feedback?

screenshot 2013-11-20 10 10 58

and

screenshot 2013-11-20 10 13 51

@portertech - updates to 0.9 and 0.10 directing users to upgrade coming soon. Really need to add anchor support to docs...

**Comment by jamtur01** [comment]
Looks good. :+1:

**Comment by ryndaniels** [comment]
Agreed.

**Comment by calebhailey** [comment]
These changes (and @kdaniels' PR) are live now: http://sensuapp.org/docs/0.12/installing_sensu :smile:

/cc @jamtur01 @portertech @nstielau

**Pull request merged**
